name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Set up Docker
                uses: docker/setup-docker@v1

            - name: Pull Docker image
                run: docker pull pengbai/docker-supermario
            - name: Run Docker image
                run: docker run pengbai/docker-supermario